travis:
  secure:
    BINSTAR_TOKEN: k9i8tBz5IL20g8WR7kA2IRomuxayg1G59u5R12y7nuZB4cCH+FU6CTIwmHd2wM5YPen0MXrqFXJWKYYEng8XWphy7zrqmrBIr4sptaV2xWamKX+YigbLFpW81/QQrtYtO7r70Cl/kA5J1a9dnuookBHUYgudPakSq+KcFbG/KBVLV6wSnfYCqmkLpDZKZHLGzw9zWOyed/zugldTzNfSXarsCBK+ViX9K+Hxj36J3S6IPDnU3ud6Ls95V80p5Idq06tbvQK7uBfpaLmPaOBm8TMjFFWgkRC5Mfmpc5/t6+Ky5/le/cz8Fc4PtxXSsq655sWX+1OAtYqu47hSYa4PUdflIaiA5dV6Z6/3YUh8TbZPUCGcYT+mbiol+tI3tToOzS7ygaOFtyKU1a8AxmQqVEKbPoV44iy5v6Oqk4Wfgz/9lzftiDHSp0dy1GxCyqvbfNI5JqMN5Kev5BrnSlgQ4PEtuFVp4RWV+9Bbzvsi3XnmyKbzEH2FiyqcsljDAFRbQ/rCV+ooYkDRwMEBYnN99TO8+fiOsljM4ySmTG4d0JM9tQsvWiIhjWYm8FPbqfbAAYProR9662uxbsKLwbI/5tMdpY8qIabhJ+1gr+Ke3fvTKAYjIwT8+yteHh9ihEfAoWjJpHEt2wuSU6wd2TOi4GwPOslvh5rBJKT3OCQ6TbM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
