travis:
  secure:
    BINSTAR_TOKEN: csKeIMp3iihJEM5z/3miyfaj8sDIpflCiCRBB5rtZpVCpW6KNBN7piO91hxNq3ZQE19M3C0DlrYDMulpnj/vDBfLMn7xa+h8HtqKT48EcIt2n/UzdZNtQKJMpYMAv0U3CQCRaU1veutzi+DMgts9VmPQPDvyYQcgSPLo5ZMz1dbIHfxmKxHH/LvHBkD7+4G8zRhgPMlmuATdmeOqgQ14PEKrPLumiWyKNXvpi1IU7SpV+bYrYMAKs778SjSACCGUlrqRl0ZPhMqVFMVjllXIM6fa0kPdAmbugDckFrSsZuPK5pHa6JsR9hSxkcAqChMnW+K92w0Aqzm808/+MT8nQA/4vPlBivGX1nlju0DyBlTrmC9QafZPu5IPLXEiscaALO5VfIvj0/GJvpAl7RyujiWjY075AQ630MqC0dQYO5h/ABG8eo2dUmJ6rLfi2FO6JMCHKryr0kM353TCITVqJX21OyaME/cPCbjegs0eYPMLkhMkUl3x920Qwr0yL5ucbVPZt8tYat3tbBGEo+WIcOxO63b2bKiJ1MdM1NWxrbk6vVB5uY3sy02v7cYlh6ZCfPtFRcy3AmtEZPLcrn564dlhCXej4gk9APjTGb6f+C+xKcBsTWdiuQQ0xq7g0wCjpK1xHBAiKcXuFivT9MWBQm3aLWZm23+unHtltWmcDJY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
